### PR TITLE
Allow running PR with full tests.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by dpiparo** [comment]
@vgvassilev , I know @amadio was profiling all tests to identify the long running ones (>5 minutes I *think*). Perhaps its' worth double checking with him.

**Comment by vgvassilev** [comment]
@dpiparo, this PR is to allow the user to instruct the bot not to skip any tests, i.e. to perform a build very close to the nightly builds. I do not see how that would be related to enabling more tests (presumably still excluding some).

**Comment by dpiparo** [comment]
@vgvassilev , the relation is that once it's possible to have all tests ran the load on the nodes will increase noticeably. In order to keep it under control it is necessary to finalise the very solid work which was started by @amadio to identify (and fix!) the long running tests.

**Comment by vgvassilev** [comment]
@dpiparo, I see. The current patch is an opt-in. It only runs them if you explicitly request it with -Dctest...=On.

**Comment by dpiparo** [comment]
@vgvassilev , definitively! it's the perfect opportunity to respawn the other activity which is, per se, very useful not only in combination with yours!

**Comment by amadio** [comment]
Isn't this enabling tests even that are not supposed to run due to build options? For example, tutorials that depend on something that is disabled.

**Comment by vgvassilev** [comment]
I do not thing so, our nightlies (a few lines below the patch) do not exclude tutorials...

**Comment by amadio** [comment]
The nightlies do exclude part of the tutorials. If you have, say minuit2 disabled, some tutorials won't run, so they have to be disabled. Just look at the total number of tests run on each nightly build, and you'll see that they vary from build to build.

**Comment by vgvassilev** [comment]
I understand that, however, the exclusions must be happening outside of ctest, otherwise we would not have successful nightlies looking at the code below.

This patch does not do anything smart: it just does what jenkins will do for regular nightly build if the user instructs the PR builder.

**Comment by vgvassilev** [comment]
ping... can we get that in, because we need it for the cxxmodules work?

**Comment by pcanal** [comment]
Where did you add documentation on how to make use this new features (aka, I am not sure that I can guess the flag to add .. and even if I did, I am sure I wont remember it long ...)

**Comment by vgvassilev** [comment]
Where should I add documentation?

**Comment by pcanal** [comment]
Probably both in the commit log and at https://github.com/phsft-bot/build-configuration/blob/master/README.md

**Comment by vgvassilev** [comment]
I do not see the bot help to enumerate all possible options we can invoke it with. I can fix the commit log OTOH.

**Comment by pcanal** [comment]
> I can fix the commit log OTOH.

Please.

> I do not see the bot help to enumerate all possible options we can invoke it with.

I suppose there is two categories.  The one from ROOT itself which are documented at <https://root.cern.ch/building-root> and the one solely for jenkins ... which I assumed would have be documented at < https://github.com/phsft-bot/build-configuration/blob/master/README.md > or at least that page would have had a pointer ...

**Pull request merged**
